version: '3.0'

services:
  ui:
    image: samtecspg/articulate-ui:0.12.1
    ports: ['0.0.0.0:3000:3000']
    networks: ['botsharp-network']
    environment:
     - API_URL

  botsharp:
    image: botsharpdocker/botsharp-rasa:latest
    ports: ['0.0.0.0:5000:5000']
    networks: ['botsharp-network']

networks: {botsharp-network: {}}
